[AMQP]


# Host information
host = "amqp.example.com"
vhost = "vhost"
port = 5671

# Username and password for the AMQP router
username = "amqpusername"
password = "amqppassword"

# What exchange and queue to create to listen on
listen_exchange = "gracc.osg.summary"
listen_queue = "gracc.osg.summary"

[PeriodicSummarizer]

request_exchange = "gracc.osg.requests"
request_key = "gracc.osg.requests"

# The job summarization
[Summary.jobs]
summary_type = "summary"

destination_exchange = "gracc.osg.summary"
destination_key = "gracc.osg.summary"

# The transfer summarization
[Summary.transfers]
summary_type = "transfer_summary"

destination_exchange = "gracc.osg.transfer-summary"
destination_key = "gracc.osg.transfer-summary"

